# .github/workflows/sync.yml
name: Daily Scraper Sync

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: node src/scraper.js
      - name: Commit updated JSON
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/district110.json
          git commit -m "Update scraped data"
          git push